config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :friends
  get 'home/index' # 127.0.0.1:3000/home/index
  # root 'home#index' # 127.0.0.1:3000 invokes views/home/index.html.erb
  root 'friends#index'
  get 'home/about'
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/friend.rb
class Friend < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :friends
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  # if user not(!) authenticated, no no further actions allowed except index and show
  before_action :validate_user, only: [:edit, :update, :destroy]

  # GET /friends or /friends.json
  def index
    if user_signed_in?
      @friends = Friend.all
    else
      render "home/index"
    end
  end

  # GET /friends/1 or /friends/1.json
  def show
  end

  # GET /friends/new
  def new
    # @friend = Friend.new
    @friend = current_user.friends.build
  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends or /friends.json
  def create
    # @friend = Friend.new(friend_params)
    @friend = current_user.friends.build(friend_params)

    respond_to do |format|
      if @friend.save
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully created." }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully updated." }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy

    # The following 6 lines are not compatible with link_to
    # @friend.destroy

    #  respond_to do |format|
    #    format.html { redirect_to friends_url, notice: "Friend was successfully destroyed." }
    #    format.json { head :no_content }
    # end

    @friend = Friend.find(params[:id])
    @friend.destroy

    redirect_to friends_path, notice:"Friend was successfully destroyed.", status: :see_other
  end

  # Validate if the current user can perform update and delete operations.
  def validate_user
    @friend = current_user.friends.find_by(id: params[:id])
    redirect_to friends_path, notice: "Not authorized to edit/delete this friend" if @friend.nil?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friend_params
      params.require(:friend).permit(:first_name, :last_name, :email, :phone, :twitter, :user_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def index
  end

  def about
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/friends/_form.html.erb
<%= form_with(model: friend) do |form| %>
  <% if friend.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
        <% friend.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.text_field :first_name, class:"form-control", placeholder:"First name" %>
  </div><p/>

  <div class="form-group">
    <%= form.text_field :last_name, class:"form-control", placeholder:"Last name" %>
  </div><p/>

  <div class="form-group">
    <%= form.text_field :email, class:"form-control", placeholder:"Email" %>
  </div><p/>

  <div class="form-group">
    <%= form.text_field :phone, class:"form-control", placeholder:"Phone" %>
  </div><p/>

  <div class="form-group">
    <%= form.text_field :twitter, class:"form-control", placeholder:"Twitter" %>
  </div><p/>

  <div class="form-group">
    <%= form.number_field :user_id, id: :friend_user_id, class:"form-control", value:current_user.id, type: :hidden %>
  </div><p/>
  
  <div>
    <%= form.submit class:"btn btn-dark" %>
  </div>
<% end %>

app/views/friends/_friend.html.erb
<div id="<%= dom_id friend %>">
  <p>
    <strong>First name:</strong>
    <%= friend.first_name %>
  </p>

  <p>
    <strong>Last name:</strong>
    <%= friend.last_name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= friend.email %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= friend.phone %>
  </p>

  <p>
    <strong>Twitter:</strong>
    <%= friend.twitter %>
  </p>

</div>

app/views/friends/edit.html.erb
<h1>Editing friend</h1>
<br>

<%= render "form", friend: @friend %>

<br>

<div>
  <%= link_to "Show this friend", @friend, class:"btn btn-secondary" %>
  <%= link_to "Back to friends", friends_path, class:"btn btn-secondary" %>
</div>

app/views/friends/index.html.erb
<table class="table table-striped table-bordered table-hover">
  <thead class="table-dark">
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Twitter</th>
      <!--<th colspan="1"></th>-->
    </tr>
  </thead>

  <tbody>
    <% @friends.each do |friend| %>
      <% if friend.user == current_user %>
      <tr>
        <td><%= link_to friend.first_name+" "+ friend.last_name, friend %></td>
        <td><%= friend.email %></td>
        <td><%= friend.phone %></td>
        <td><%= friend.twitter %></td>
        <!--<td><%= link_to "Edit", edit_friend_path(friend) %></td>-->
        <!--<td><%= link_to "Delete", friend, data: {
          turbo_method: :delete,
          turbo_confirm: "Are you sure?"
        }, class:"btn btn-outline-danger btn-sm"%></td>-->

        <!--alternative delete-->
        <!--<td><%= button_to "Destroy this friend", friend, method: :delete, form: {data: {turbo_confirm: 'Are you sure?'}} %></td>-->
      </tr>
      <% end %>
    <% end %>
  </tbody>

</table>

<%= link_to "New friend", new_friend_path, class:"btn btn-dark" %>

app/views/friends/new.html.erb
<h1>New friend</h1>
<br>

<%= render "form", friend: @friend %>

<br>

<div>
  <%= link_to "Back to friends", friends_path, class:"btn btn-secondary" %>
</div>

app/views/friends/show.html.erb
<div class="p-5 mb-4 bg-light rounded-3">
  <div class="container-fluid py-5">
    <h1 class="display-5 fw-bold">
      <%= @friend.first_name %> <%= @friend.last_name %>
    </h1>
    <p class="col-md-8 fs-4">
      <%= @friend.email %> |
      <%= @friend.phone %> |
      <%= @friend.twitter %>
    </p>
    <br>
    
    <%= link_to "Edit", edit_friend_path(@friend), class:"btn btn-dark" %>
  
    <%= link_to "Delete", @friend, data: {
      turbo_method: :delete,
      turbo_confirm: "Are you sure?"
    }, class:"btn btn-danger" %>
  
    <%= link_to "Friends", friends_path, class:"btn btn-dark" %>
  
    <!--alternative delete-->
    <%#= button_to "Destroy this friend", @friend, method: :delete, form: {data: {turbo_confirm: 'Are you sure?'}} %>

  </div>
</div>

app/views/home/about.html.erb
<div class="card mb-3" style="max-width: 660px;">
  <div class="row g-0">

    <div class="col-md-4">
      <%=image_tag("AboutPage.jpg", class:"img-fluid rounded-start")%>
    </div>

    <div class="col-md-8">
      <div class="card-body">
        <h5 class="card-title">About this APP</h5>
        <p class="card-text">The author of the app is Eric Young. The app is built with Ruby on Rails.</p>

        <button type="button" class="btn btn-dark"
        style="--bs-btn-padding-y: .25rem; --bs-btn-padding-x: .5rem; --bs-btn-font-size: 1rem;">
        <%= link_to "Home Page", home_index_path, class:"nav-link" %>
        </button>
      </div>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<div class="card text-center" style="width: 18rem;">
  <%=image_tag("HomePage.jpg")%>

  <div class="card-body">
    <h5 class="card-title">Welcome to Friend List!</h5>
    <p class="card-text">This app helps you record the contact information of your friends.</p>

    <button type="button" class="btn btn-secondary"
        style="--bs-btn-padding-y: .25rem; --bs-btn-padding-x: .5rem; --bs-btn-font-size: 1rem;">
        <%= link_to "Sign Up", new_user_registration_path, class:"nav-link" %>
    </button>

    <button type="button" class="btn btn-dark"
        style="--bs-btn-padding-y: .25rem; --bs-btn-padding-x: .5rem; --bs-btn-font-size: 1rem;">
        <%= link_to "Sign In", new_user_session_path, class:"nav-link" %>
    </button>
  </div>
</div>

app/views/layouts/_alert.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to "Friend List", root_path, class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">

        <li class="nav-item">
          <%= link_to "About", home_about_path, class:"nav-link" %>
        </li>

        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Sign Out", destroy_user_session_path, data: {turbo_method: :delete}, class:"nav-link" %>
            <!--The following line does NOT work -->
            <%#= link_to "Sign Out", destroy_user_session_path, method: :delete, class:"nav-link" %>
          </li>
        <% end %>

      </ul>

      <% if user_signed_in? %>
        <button type="button" class="btn btn-light"
          style="--bs-btn-padding-y: .25rem; --bs-btn-padding-x: .5rem; --bs-btn-font-size: 1rem;">
          <%= link_to "Profile of " + current_user.email, edit_user_registration_path%>
        </button>
      <% end %>

    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Friends</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <%= javascript_importmap_tags %>
  </head>
  <body>

    <%=render "layouts/navbar" %>
    <div class="container">
      <br>
      <% if notice %>
        <%= render "layouts/alert" %>
      <% end %>
      <%= yield %>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
  </body>
</html>